"""Single source of truth for roles. The sign-up page reads this through GET /api/roles."""
ROLE_PROFILES = {
    "ML Engineer": {"summary": "Builds, evaluates and ships machine-learning models that keep working in production.",
        "skills": ["Python", "Pandas", "Machine Learning", "SQL", "Docker", "FastAPI"],
        "tools": ["scikit-learn", "PyTorch", "MLflow", "Docker"],
        "projects": ["A model served behind a validated API", "A monitoring and re-training pipeline"]},
    "AI Engineer": {"summary": "Builds applications on top of language models and checks whether they behave.",
        "skills": ["Python", "LLM Apps", "Prompting", "FastAPI", "Evaluation", "Docker"],
        "tools": ["LLM APIs", "Ollama", "Vector databases", "FastAPI"],
        "projects": ["A retrieval-based assistant with an evaluation set", "An agent with safe tool permissions"]},
    "Data Scientist": {"summary": "Finds patterns in data, tests hypotheses and explains results to decision makers.",
        "skills": ["Python", "Pandas", "Statistics", "Machine Learning", "SQL", "Visualization"],
        "tools": ["Jupyter", "pandas", "scikit-learn", "matplotlib"],
        "projects": ["An A/B test analysis with a written conclusion", "A churn model with error analysis"]},
    "Data Analyst": {"summary": "Turns raw data into clear reports and dashboards that answer business questions.",
        "skills": ["SQL", "Excel", "Statistics", "Visualization", "Pandas"],
        "tools": ["SQL", "Excel", "Power BI or Tableau", "pandas"],
        "projects": ["A sales dashboard with a documented data source", "A cohort retention analysis"]},
    "Backend Developer": {"summary": "Designs and runs the servers, APIs and databases behind applications.",
        "skills": ["Python", "APIs", "SQL", "Authentication", "Testing", "Docker"],
        "tools": ["FastAPI or Django", "PostgreSQL", "Docker", "pytest"],
        "projects": ["A REST API with auth and tests", "A service with rate limiting and logging"]},
    "Full-Stack Developer": {"summary": "Builds complete features from the database to the screen.",
        "skills": ["JavaScript", "React", "APIs", "SQL", "Testing", "Docker"],
        "tools": ["React / Next.js", "Node or Python API", "PostgreSQL", "Docker"],
        "projects": ["A full CRUD app with sign-in", "A deployed app with CI"]},
    "Frontend Developer": {"summary": "Builds fast, accessible interfaces people enjoy using.",
        "skills": ["JavaScript", "React", "CSS", "Accessibility", "Testing", "Performance"],
        "tools": ["React", "TypeScript", "Playwright", "Lighthouse"],
        "projects": ["An accessible component library", "A dashboard with charts and loading states"]},
    "Python Developer": {"summary": "Writes reliable, tested, well-packaged Python for tools, services and automation.",
        "skills": ["Python", "Testing", "APIs", "SQL", "Packaging"],
        "tools": ["pytest", "FastAPI", "SQLite or PostgreSQL", "pip / pyproject"],
        "projects": ["A packaged CLI tool with tests", "An API with a database"]},
    "DevOps Engineer": {"summary": "Automates building, shipping and monitoring software.",
        "skills": ["Linux", "Docker", "CI/CD", "Cloud", "Monitoring", "Scripting"],
        "tools": ["Docker", "GitHub Actions", "Terraform", "Prometheus"],
        "projects": ["A CI pipeline that tests and deploys", "A monitored service with alerts"]},
    "Cybersecurity": {"summary": "Finds and fixes weaknesses before attackers use them.",
        "skills": ["Networking", "Linux", "Web Security", "Cryptography", "Incident Response", "Scripting"],
        "tools": ["Wireshark", "Burp Suite", "nmap", "OWASP guides"],
        "projects": ["A write-up of a web-app vulnerability and its fix", "A small log-analysis detector"]},
}